// Dados preservados do protótipo original; revisar antes de publicar.
const SERVICES = [
  {
    id: 1,
    name: "Clínica-Escola de Nutrição UFRJ",
    type: "Clínica-Escola",
    isFree: true,
    audience: "Comunidade em geral",
    address: "Av. Carlos Chagas Filho, 373",
    neighborhood: "Ilha do Fundão",
    city: "Rio de Janeiro",
    state: "RJ",
    phone: "(21) 3938-6700",
    isWhatsApp: false,
    hours: "Seg a Sex, 8h às 16h",
    howToRequest: "Presencialmente ou por telefone",
    contactLink: "https://nutricao.ufrj.br",
    lastUpdated: "01/08/2024",
  },
  {
    id: 2,
    name: "UBS Jardim das Flores – Serviço de Nutrição",
    type: "Serviço SUS",
    isFree: true,
    audience: "Usuários do SUS cadastrados",
    address: "Rua das Flores, 450",
    neighborhood: "Jardim das Flores",
    city: "São Paulo",
    state: "SP",
    phone: "(11) 4567-8901",
    isWhatsApp: false,
    hours: "Seg a Qui, 7h às 17h",
    howToRequest: "Encaminhamento médico ou diretamente na UBS",
    lastUpdated: "15/07/2024",
  },
  {
    id: 3,
    name: "Projeto NutriComunidade UNICAMP",
    type: "Projeto Universitário",
    isFree: true,
    audience: "Famílias em situação de vulnerabilidade",
    address: "Rua Tessália Vieira de Camargo, 126",
    neighborhood: "Barão Geraldo",
    city: "Campinas",
    state: "SP",
    phone: "(19) 98765-4321",
    isWhatsApp: true,
    hours: "Ter e Qui, 14h às 18h",
    howToRequest: "Via WhatsApp ou e-mail para nutricomun@unicamp.br",
    lastUpdated: "20/08/2024",
  },
  {
    id: 4,
    name: "Consultório Social de Nutrição – ONG VidaSaúde",
    type: "Ação Comunitária",
    isFree: false,
    costValue: "R$ 30,00 / consulta",
    audience: "Adultos e idosos",
    address: "Rua Esperança, 88",
    neighborhood: "Vila Nova",
    city: "Belo Horizonte",
    state: "MG",
    phone: "(31) 99123-4567",
    isWhatsApp: true,
    hours: "Sábados, 8h às 12h",
    howToRequest: "Agendamento via WhatsApp",
    lastUpdated: "10/09/2024",
  },
  {
    id: 5,
    name: "Ambulatório de Nutrição – HC FMUSP",
    type: "Hospital Universitário",
    isFree: true,
    audience: "Pacientes com encaminhamento médico",
    address: "Av. Dr. Enéas de Carvalho Aguiar, 155",
    neighborhood: "Cerqueira César",
    city: "São Paulo",
    state: "SP",
    phone: "(11) 2661-6000",
    isWhatsApp: false,
    hours: "Seg a Sex, 7h às 16h",
    howToRequest: "Encaminhamento médico pelo sistema SUS",
    lastUpdated: "05/08/2024",
  },
  {
    id: 6,
    name: "Núcleo de Nutrição UFMG – Ambulatório Comunitário",
    type: "Clínica-Escola",
    isFree: false,
    costValue: "R$ 20,00 / consulta",
    audience: "Comunidade em geral",
    address: "Av. Antônio Carlos, 6627",
    neighborhood: "Pampulha",
    city: "Belo Horizonte",
    state: "MG",
    phone: "(31) 3409-9826",
    isWhatsApp: false,
    hours: "Seg a Sex, 8h às 17h",
    howToRequest: "Agendamento presencial ou por telefone",
    contactLink: "https://farmacia.ufmg.br",
    lastUpdated: "25/08/2024",
  },
  {
    id: 7,
    name: "Serviço de Nutrição e Dietética – HUUFMA",
    type: "Hospital Universitário",
    isFree: true,
    audience: "Pacientes internados e ambulatorial com encaminhamento",
    address: "Rua Barão de Itapary, 227",
    neighborhood: "Centro",
    city: "São Luís",
    state: "MA",
    phone: "(98) 3272-8100",
    isWhatsApp: false,
    hours: "Seg a Sex, 7h às 13h",
    howToRequest: "Encaminhamento pelo sistema de saúde do Maranhão",
    lastUpdated: "12/08/2024",
  },
  {
    id: 8,
    name: "NutriVida Fortaleza – Extensão UFC",
    type: "Projeto Universitário",
    isFree: true,
    audience: "Moradores de comunidades periféricas",
    address: "Rua Coronel Nunes de Melo, 1127",
    neighborhood: "Rodolfo Teófilo",
    city: "Fortaleza",
    state: "CE",
    phone: "(85) 99876-5432",
    isWhatsApp: true,
    hours: "Quintas, 13h às 17h",
    howToRequest: "Inscrição via WhatsApp com nome e CPF",
    lastUpdated: "03/09/2024",
  },
];
// Exemplos fictícios para demonstrar os filtros, sem contatos reais.
SERVICES.push(...[
  ['UBS Cuidar — Orientação Nutricional', 'Serviço SUS', 'Recife', 'PE', true, 'Famílias cadastradas na atenção básica'],
  ['Centro de Saúde Bem Viver', 'Serviço SUS', 'Curitiba', 'PR', true, 'Adultos e idosos'],
  ['Projeto Universidade à Mesa', 'Projeto Universitário', 'Salvador', 'BA', true, 'Comunidade em geral'],
  ['Projeto Nutrição na Comunidade', 'Projeto Universitário', 'Belém', 'PA', true, 'Famílias em situação de vulnerabilidade'],
  ['Ação Social Prato Solidário', 'Ação Social', 'Teresina', 'PI', true, 'Famílias de baixa renda'],
  ['Programa Social Cuidar da Alimentação', 'Ação Social', 'Manaus', 'AM', false, 'Adultos e idosos'],
  ['Coletivo Alimentar Bem', 'Ação Comunitária', 'Recife', 'PE', true, 'Moradores da comunidade'],
  ['Associação Comunidade Saudável', 'Ação Comunitária', 'Salvador', 'BA', false, 'Comunidade em geral'],
  ['Hospital Universitário — Ambulatório Escola de Nutrição', 'Hospital Universitário', 'Curitiba', 'PR', true, 'Pacientes com encaminhamento'],
  ['Hospital Universitário — Programa de Cuidado Alimentar', 'Hospital Universitário', 'Belém', 'PA', true, 'Pacientes em acompanhamento ambulatorial']
].map(([name, type, city, state, isFree, audience], index) => ({
  id: index + 9, name, type, city, state, isFree, audience,
  isExample: true, address: 'Endereço ilustrativo', neighborhood: 'Centro',
  phone: '', isWhatsApp: false, hours: 'Horários a definir neste exemplo',
  costValue: isFree ? undefined : 'R$ 25,00 / consulta (ilustrativo)',
  howToRequest: 'Exemplo demonstrativo, sem agendamento disponível.',
  lastUpdated: ''
})));

const ARTICLES = [
  {
    id: 1,
    title: "5 alimentos que fortalecem sua imunidade",
    author: "Dra. Ana Lima",
    credential: "Nutricionista • CRN-3 12345",
    category: "Imunidade",
    excerpt:
      "Conheça os alimentos mais poderosos para fortalecer suas defesas e como incluí-los no dia a dia com praticidade e baixo custo.",
    readTime: "4 min",
    imageUrl:
      "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=600&h=360&fit=crop&auto=format",
  },
  {
    id: 2,
    title: "Como se alimentar bem com pouco dinheiro",
    author: "Dr. Carlos Mendes",
    credential: "Nutricionista • CRN-6 67890",
    category: "Alimentação Acessível",
    excerpt:
      "Dicas práticas e cardápios econômicos que garantem todos os nutrientes sem pesar no bolso da família.",
    readTime: "6 min",
    imageUrl:
      "https://images.unsplash.com/photo-1579113800032-c38bd7635818?w=600&h=360&fit=crop&auto=format",
  },
  {
    id: 3,
    title: "Alimentação saudável na gestação: guia completo",
    author: "Dra. Fernanda Costa",
    credential: "Nutricionista • CRN-8 11223",
    category: "Gestação",
    excerpt:
      "O que comer — e o que evitar — durante a gravidez para garantir a saúde da mãe e o desenvolvimento saudável do bebê.",
    readTime: "8 min",
    imageUrl:
      "https://images.unsplash.com/photo-1610348725531-843dff563e2c?w=600&h=360&fit=crop&auto=format",
  },
  {
    id: 4,
    title: "Segurança alimentar: direito de todos",
    author: "Prof. Dr. João Silva",
    credential: "Pesquisador em Nutrição • UFRJ",
    category: "Política de Saúde",
    excerpt:
      "Entenda o conceito de segurança alimentar, os direitos garantidos pela lei e como a nutrição pode ser uma ferramenta de cidadania.",
    readTime: "5 min",
    imageUrl:
      "https://images.unsplash.com/photo-1490818387583-1baba5e638af?w=600&h=360&fit=crop&auto=format",
  },
];
